Django/ActivityManagementSystem/Assignment_1/urls.py
from django.contrib import admin
from django.urls import path
from ams import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('child/profile', views.child_profile, name='child-profile'),
    path('addactivity', views.add_activity, name='add-activity'),
    path('myprofile/', views.my_profile, name='my-profile'),

    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('remove/child/', views.remove_child, name='remove-child'),
    path('update/child/', views.updateChild, name='update-child')




]

ass1/urls.py
from django.contrib import admin
from django.urls import path

from ams import views

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('child/profile/', views.child_profile, name='child-profile'),
    path('addactivity/', views.add_activity, name='add-activity'),
    path('myprofile/', views.my_profile, name='my-profile'),
    path('remove/child/', views.remove_child, name = 'remove-child'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register-user'),
    
    path('update/child/', views.updateChild, name = 'update-child'),
    path('calendar/', views.calendar, name = 'calendar'),
    path('supervise/', views.supervise, name = 'supervise'),


    path('distance/',views.distance, name = 'distance'),



    path('forgot/',
        auth_views.PasswordResetView.as_view(template_name="forgot.html"),
        name="forgot"),

    path('reset_password_sent/',
            auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"),
            name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"),
        name="password_reset_confirm"),

    path('reset_password_complete/',
            auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"),
            name="password_reset_complete"),

]

Django/ActivityManagementSystem/ams/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class Role(models.Model):
    '''
    The Role entries are managed by the system,
    automatically created via a Django data migration.
    '''
    TEACHER = 1
    PARENT = 2

    ROLE_CHOICES = (
        (PARENT, 'parent'),
        (TEACHER, 'teacher'),

    )

    id = models.PositiveSmallIntegerField(
        choices=ROLE_CHOICES, primary_key=True)

    def __str__(self):
        return self.get_id_display()


class Activity(models.Model):
    name = models.CharField(max_length=255)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    def __str__(self):
        return self.name


class Child(models.Model):
    name = models.CharField(max_length=50)
    # age = models.IntegerField()
    date_of_birth = models.DateField()
    address = models.CharField(max_length=255)
    contact = models.CharField(max_length=15)
    enrolled_activities = models.ManyToManyField(
        Activity, blank=True)


class User(AbstractUser):
    roles = models.ManyToManyField(Role)
    myChildren = models.ManyToManyField(Child, blank=True)

    def __str__(self):
        return self.username

Django/ActivityManagementSystem/ams/forms.py
from django.forms import ModelForm
from .models import Child, Activity
from django import forms
from Assignment_1 import settings


# Create the form class.


class DateInput(forms.DateInput):
    input_type = 'date'


class ChildForm(ModelForm):
    class Meta:
        model = Child
        fields = ['name', 'date_of_birth',
                  'address', 'contact']
        widgets = {
            'date_of_birth': DateInput(),
        }


# class ChildUpdateForm(forms.ModelForm):
#     class Meta:
#         model = Child
#         fields = ['name', 'age', 'date_of_birth', 'address', 'contact']
#         widgets = {
#             'date_of_birth': DateInput(),
#         }

class DateTimeInput(forms.DateTimeInput):
    input_type = 'datetime-local'

class ActivityForm(ModelForm):
    class Meta:
        model = Activity

        fields = ['name', 'start_time', 'end_time']
        widgets = {
            'start_time': DateTimeInput(),
            'end_time': DateTimeInput(),
        }

Django/ActivityManagementSystem/ams/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import User, Role, Activity, Child
from django.db import IntegrityError
from .import forms




def child_profile(request, context = {}):
    child = ""


    if request.method == 'POST':
        child = request.user.myChildren.all().filter(id=request.POST.get('childId')).first()
    context = {'includeNav':True, 'child':child}

    return render(request, 'child-profile.html', context)


def add_activity(request):
    return render(request, 'add-activity.html', {'includeNav': True})


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.add_message(request, messages.INFO,
                                 "Please check your username and/or password")

    return render(request, 'login.html', {'includeNav': False})


def logout_view(request):
    if (request.user.is_authenticated):
        logout(request)

    return redirect('login')


def my_profile(request):
    try:
        userrole = request.user.roles.first().id
    except:
        userrole = '3'
    cf = forms.ChildForm()

    if request.method == 'POST':
        cf = forms.ChildForm(request.POST)
        if cf.is_valid():
            child = cf.save()
            request.user.myChildren.add(child)
            messages.add_message(request, messages.SUCCESS,
                                 "Child added successfully")
        else:
            messages.add_message(request, messages.INFO,
                                 "Child Add Failed")

    myChildren = request.user.myChildren.all()

    context = {'userrole':userrole, 'includeNav': True, 'myChildren': myChildren, 'form': cf}

    return render(request, 'my-profile.html', context)


def register_view(request):
    if(request.user.is_authenticated):
        return redirect('home')
    try:
        if (request.method == 'POST'):
            username = request.POST.get("username")
            password = request.POST.get("password")
            email = request.POST.get("email")
            userType = request.POST.get("userType")
            user = User.objects.create_user(username, email, password)
            print(userType)
            if user is not None:
                # messages.add_message(request, level, message, extra_tags='', fail_silently=False)
                user.roles.add(Role.objects.get(id=userType))
                messages.add_message(
                    request, messages.INFO, "your account was created successfully please log in now")
                # A backend authenticated the credentials
                return redirect('login')
    except IntegrityError:
        messages.add_message(
            request, messages.INFO, "That Username is taken please try another username")
    return render(request, 'register.html', {'includeNav': False})


def remove_child(request):
    if request.method == 'POST':
        childId = request.POST.get('childId')
        request.user.myChildren.filter(id=childId).delete()
        messages.add_message(request, messages.SUCCESS,
                             "Child deleted successfully")
    else:
        messages.add_message(request, messages.INFO,
                             "Child remove Failed")
    return redirect('my-profile')


def updateChild(request):
    if (not request.user.is_authenticated):
        return redirect('home')
    context = {}

    if request.method == 'POST':
        childId = request.POST.get('childId')
        child = request.user.myChildren.filter(id=childId).first()
        cf = forms.ChildForm(request.POST, instance=child)
        if cf.is_valid():
            cf.save()
            messages.success(
                request, f'{child.name}\'s details have been Updated Successfully!')
            return redirect('my-profile')
    else:
        cf = forms.ChildForm()
        messages.add_message(request, messages.INFO, 'Failed to update child details.')
        

    context['form'] = cf
    return render(request, 'my-profile.html', context)


def home(request):
    try:
        userrole = request.user.roles.first().id
    except:
        userrole = '3'
    af = forms.ActivityForm()
    allActivities = Activity.objects.all()

    
    if request.method == 'POST':
        if request.POST.get('childId') is not None:
            try:
                childId= request.POST.get('childId')
                activityId= request.POST.get('activityId')
                selectedChild = Child.objects.filter(id=childId).first()
                selectedActivity = Activity.objects.filter(id=activityId).first()
                selectedChild.enrolled_activities.add(selectedActivity)
                messages.add_message(request, messages.SUCCESS, f'{selectedChild.name} has been enrolled in {selectedActivity.name}')
            except:
                messages.add_message(request, messages.INFO, f'FAILED to enroll child')
            context = {'userrole':userrole,'includeNav':True, 'child':selectedChild, 'allAticvities':allActivities}

            response = child_profile(request, context)
            return response
        else:
            af = forms.ActivityForm(request.POST)
            if af.is_valid():
                af.save()
                messages.add_message(request, messages.SUCCESS,"Activity added successfully")
            else:
                messages.add_message(request, messages.INFO,"Activity  Failed")
    context = {'userrole':userrole,'includeNav':True,'form':af,'allActivities': allActivities}
    return render(request,'home.html',context)

Django/ActivityManagementSystem/templates/add-activity-modal.html
{%load crispy_forms_tags %}


<div id="add-activity-modal" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add Activity</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
            </div>
            <form method="POST">


                <div class="modal-body">

                    {{form|crispy}} {%csrf_token%}
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-secondary">Add Activity</button>
            </form>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

            </div>
        </div>
    </div>
</div>

Django/ActivityManagementSystem/templates/add-activity.html
{% extends 'base.html'%} {% block content1 %} hi im the Register page without the navbar {% endblock%}

Django/ActivityManagementSystem/templates/add-child-modal.html
 {%load crispy_forms_tags %}


<div id="add-child-modal" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add Child</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
            </div>
            <form method="POST">


                <div class="modal-body">

                    {{form|crispy}} {%csrf_token%}
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-secondary">Add Child</button>
            </form>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

            </div>
        </div>
    </div>
</div>

Django/ActivityManagementSystem/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!--Fontawesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <title>Change me</title>
</head>


<body>

    {%if includeNav %} {% include 'nav.html'%} {% endif %} {% if messages %}
    <div class="messages mt-1">
        {% for message in messages %}
        <div{% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}><strong>{{ message.tags }}</strong>! {{message}}</div>
    {% endfor %}
    </div>
    {% endif %} {% block content1 %} {% endblock%}
    <script>
        $('.modal').appendTo($('main'));
    </script>
</body>

Django/ActivityManagementSystem/templates/child-profile.html
{% extends 'base.html'%} {% block content1 %}
<main>

    <div class="container">

        <div class="row my-5 week-nav">
            <div class="col">
                <div class="row">
                    <div class="col">
                        <p class="mb-3" style="text-align: center;">This week's activities for your child: 22/4/2020 tp 29/04/2020</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <button class="btn btn-outline-secondary">Previous</button>
                    </div>
                    <div class="col">
                        <button class="btn btn-outline-secondary float-right">Next</button>

                    </div>

                </div>

            </div>





        </div>

        <div class="row">
            <div class="col-3">
                <div class="profile">
                    <div class="card">
                        <img src="https://source.unsplash.com/random" class="card-img-top" alt="{{child.name}} PROFILE">
                        <div class="card-body">
                            <h5 class="card-title">{{child.name}}'s Profile</h5>
                        </div>
                        <ul class="list-group mt-3">
                            <li class="list-group-item">DOB and Age: {{child.date_of_birth}}</li>
                            <li class="list-group-item">Address: {{child.address}}</li>
                            <li class="list-group-item"><a href="">Parent's contact</a></li>
                            <li class="list-group-item">Teacher's contact</li>
                        </ul>
                    </div>
                </div>
            </div>

            <style>
                .activity {
                    background-color: #e8e8e8;
                    border: 1px solid black;
                }
                
                .activity button {
                    padding: 0 5px 0 5px;
                    margin-bottom: 10px;
                }
            </style>

            <div class="col-9">
                <div class="row activities">
                    {%for activity in child.enrolled_activities.all%}
                    <div class="col-sm-6">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Activity: {{activity.name}}</h5>

                                <p class=""> {{activity.name}} </p>
                                <p>From: {{activity.start_time}} </p>
                                <p>To: {{activity.end_time}} </p>



                            </div>



                        </div>
                    </div>
                    {% endfor %}




                </div>

</main>
{%include 'success-modal.html' %} {% endblock%}

Django/ActivityManagementSystem/templates/home.html
{% extends 'base.html'%} {% block content1 %}
<main>
    <div class="container d-flex flex-column">

        <div class="row mb-1 mt-5 week-nav">
            <div class="col">
                <button class="btn btn-outline-secondary">Previous</button>
            </div>

            <div class="col">
                <p style="text-align: center;">This week's activities</p>
            </div>
            <div class="col">
                <button class="btn btn-outline-secondary float-right">Next</button>

            </div>
        </div>
        {%if userrole is 1%}
        <button class="btn my-4 ml-auto btn-secondary" data-toggle="modal" data-target="#add-activity-modal"><i
            class="fa fa-plus"></i>Add Activity</button> {%include 'add-activity-modal.html'%} {%endif%}
        <style>
            .activity {
                background-color: #e8e8e8;
                border: 1px solid black;
            }
            
            .activity button {
                padding: 0 5px 0 5px;
                margin-bottom: 10px;
            }
        </style>

        <div class="row">
            {%for activity in allActivities%}
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Activity: {{activity.name}}</h5>

                        <p class=""> {{activity.name}} </p>
                        <p>From: {{activity.start_time}} </p>
                        <p>To: {{activity.end_time}} </p>
                        {%if userrole is 2 %} {%if user.myChildren.count > 0%}
                        <button data-toggle="dropdown" class="btn btn-primary float-right"><i class="fa fa-caret-down"></i>Enroll My Child</button>

                        <!--aria-haspopup="true" aria-expanded="false"-->

                        <div style="background: transparent;border:none;" class="dropdown-menu">
                            {%for child in user.myChildren.all%}
                            <form method="post">
                                {%csrf_token%}
                                <input name="childId" value="{{child.id}}" type="hidden">
                                <input name="activityId" value="{{activity.id}}" type="hidden">
                                <button type="submit" class="btn mb-1 btn-outline-secondary">{{child.name}}</button><br>


                            </form>
                            {% endfor %}
                        </div>
                        {%else%}
                        <button data-toggle="dropdown" class="btn btn-primary float-right"><i class="fa fa-caret-down"></i>You do not have any children to enroll</button> {%endif%} {%endif%}
                    </div>
                </div>
            </div>
            {%endfor%}
        </div>



    </div>
</main>

{% endblock%}

Django/ActivityManagementSystem/templates/login.html
{% extends 'base.html'%} {% block content1 %}

<style>
    @import url('https://fonts.googleapis.com/css?family=Numans');
    html,
    body {
        background: url('https://cdn.dribbble.com/users/247458/screenshots/2503828/pattern.jpg');
        overflow: hidden;
        height: 100%;
        font-family: 'Numans', sans-serif;
    }
    
    .container {
        margin-top: 10%;
        height: 100%;
        align-content: center;
    }
    
    .card {
        height: 370px;
        margin-top: auto;
        margin-bottom: auto;
        width: 400px;
        background-color: rgba(0, 0, 0, 0.5) !important;
    }
    
    .social_icon span {
        font-size: 60px;
        margin-left: 10px;
        color: #FFC312;
    }
    
    .social_icon span:hover {
        color: white;
        cursor: pointer;
    }
    
    .card-header h3 {
        color: white;
    }
    
    .social_icon {
        position: absolute;
        right: 20px;
        top: -45px;
    }
    
    .input-group-prepend span {
        width: 50px;
        color: black;
        border: 0 !important;
    }
    
    input:focus {
        outline: 0 0 0 0 !important;
        box-shadow: 0 0 0 0 !important;
    }
    
    .remember {
        color: white;
    }
    
    .remember input {
        width: 20px;
        height: 20px;
        margin-left: 15px;
        margin-right: 5px;
    }
    
    .login_btn {
        color: black;
        background-color: #FFC312;
        width: 100px;
    }
    
    .login_btn:hover {
        color: black;
        background-color: white;
    }
    
    .links {
        color: white;
    }
    
    .links a {
        margin-left: 4px;
    }
</style>

<main>
    <div class="container">
        <div class="d-flex justify-content-center h-100">
            <div class="card">
                <div class="card-header">
                    <h3>Sign In</h3>

                </div>
                <div class="card-body">
                    <form method="post">
                        {%csrf_token%}
                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            <input name="username" type="text" class="form-control" placeholder="username">

                        </div>
                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            <input name="password" type="password" class="form-control" placeholder="password">
                        </div>
                        <div class="row align-items-center remember">

                        </div>
                        <div class="form-group">
                            <input type="submit" value="Login" class="btn float-right btn btn-primary">
                        </div>
                    </form>
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-center links">
                        Don't have an account?<a href="{% url 'register' %}">Sign Up</a>
                    </div>
                    <div class="d-flex justify-content-center">
                        <a href="#">Forgot your password?</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>


{% endblock%}

Django/ActivityManagementSystem/templates/my-profile.html
{% extends 'base.html'%} {% block content1 %}

<!-- 
 - Edit the parents details like name, first name, address, phone, email, city, country
 - Add a child button 
 - profile Picture
 - view list of my children section
 - update child information (adress, contact)

 
-->

<main>
    {%include 'add-child-modal.html'%}

    <div class="container d-flex flex-column">
        <h1>My details</h1>
        <p>I am a {{user.roles.first}}and my name is {{user.username}}</p>
        {%if userrole is 2%}
        <h1>MY CHILDREN</h1>
        <button class="btn my-4 ml-auto btn-secondary" data-toggle="modal" data-target="#add-child-modal"><i
            class="fa fa-plus"></i>Add Child</button>



        <div class="list-group my-children-list">
            {%for child in myChildren%}
            <div class="list-group-item list-group-item-action d-flex flex-column align-items-start ">

                <h5 class="mb-1 ">{{child.name}}</h5>
                <p>Address: {{child.address}}</p>
                <p>Date of birth: {{child.date_of_birth}}</p>
                <p>Contact: {{child.contact}}</p>
                <div class="button-group ml-auto">


                    <form method="post" action="{% url 'child-profile' %}">
                        {%csrf_token%}
                        <input name='childId' value="{{child.id}}" type="hidden">
                        <button type="submit" value="{{child.id}}" class="btn btn-primary float-right" href="">view child profile </button><br/>
                    </form>
                    <button class="btn btn-secondary " data-toggle="dropdown">Action <i class="fa fa-caret-down"></i>
                    </button>

                    <!--aria-haspopup="true" aria-expanded="false"-->

                    <div style="background: transparent;border:none;" class="dropdown-menu">
                        <a name="childId" value="{{child.id}}" class="btn mb-1 btn-secondary" data-toggle="modal" data-target="#update-child-modal-{{child.id}}"><i class="fas fa-edit"></i> Update</a><br> {%include 'update-child-modal.html'%}
                        <a class="btn btn-danger" data-toggle="modal" data-target="#removeChildModal-{{child.id}}"><i class="fas fa-trash"></i> Remove</a> {%include 'remove-child-modal.html'%}
                    </div>
                </div>



            </div>
            {%endfor%}

        </div>
        {%endif%}
    </div>


</main>
{%endblock%}

Django/ActivityManagementSystem/templates/remove-child-modal.html
<div id="removeChildModal-{{child.id}}" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Remove Child</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this child?</p>
            </div>
            <form method="post" action="{% url 'remove-child'%}">
                {% csrf_token%}
                <div class="modal-footer">
                    <button name="childId" value="{{child.id}}" type="submit" class="btn btn-primary">Confirm</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

                </div>
            </form>
            <!-- End of modals-->
        </div>
    </div>
</div>

Django/ActivityManagementSystem/templates/update-child-modal.html
{%load crispy_forms_tags %}


<div id="update-child-modal-{{child.id}}" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Update Child</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
            </div>
            <form method="POST" action="{% url 'update-child'%}">


                <div class="modal-body">

                    <div id="div_id_name" class="form-group"> <label for="id_name" class=" requiredField">
                        Name<span class="asteriskField">*</span> </label>
                        <div class=""> <input value="{{child.name}}" type="text" name="name" maxlength="50" class="textinput textInput form-control" required="" id="id_name"> </div>
                    </div>
                    <div id="div_id_age" class="form-group"> <label for="id_age" class=" requiredField">
                        Age<span class="asteriskField">*</span> </label>
                        <div class=""> <input value="{{child.age}}" type="number" name="age" class="numberinput form-control" required="" id="id_age"> </div>
                    </div>
                    <div id="div_id_date_of_birth" class="form-group"> <label for="id_date_of_birth" class=" requiredField">
                        Date of birth<span class="asteriskField">*</span> </label>
                        <div class=""> <input value="{{child.date_of_birth}}" type="date" name="date_of_birth" class="dateinput form-control" required="" id="id_date_of_birth"> </div>
                    </div>
                    <div id="div_id_address" class="form-group"> <label for="id_address" class=" requiredField">
                        Address<span class="asteriskField">*</span> </label>
                        <div class=""> <input value="{{child.address}}" type="text" name="address" maxlength="255" class="textinput textInput form-control" required="" id="id_address"> </div>
                    </div>
                    <div id="div_id_contact" class="form-group"> <label for="id_contact" class=" requiredField">
                        Contact<span class="asteriskField">*</span> </label>
                        <div class=""> <input value="{{child.contact}}" type="text" name="contact" maxlength="15" class="textinput textInput form-control" required="" id="id_contact"> </div>
                    </div>
                    <input type="hidden" name="csrfmiddlewaretoken" value="kGJQx3soRaAYjWClAqPMYUrhinrWmVhHUCRH2YXA32ewn7URsjm0PgUkNqHqhphA">
                </div>
                <div class="modal-footer">
                    <button name="childId" value="{{child.id}}" type="submit" class="btn btn-secondary">Update Child</button>
            </form>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

            </div>
        </div>
    </div>
</div>